sic_pw: "vpn123"
timezone: "US / Eastern"
admin_password: "Checkpoint123!"
mgmt_user: "cpadmin"
mgmt_password: "Checkpoint123!"
ansible_user: "ansible"
ansible_user_password: "Checkpoint123!"
grub_password: "Checkpoint123!"
domain_name: "xcpng.lab"
dns_server_primary: "8.8.8.8"
dns_server_secondary: "8.8.4.4"
dns_server_tertiary: "9.9.9.9"
sms_system_name: "sms"
sms_ip: "192.168.41.20"
sms_ip_masklen: 24
sms_default_gateway: "192.168.41.1"
